"""Generate data/AircraftDB.gd from researched aircraft specs JSON.

Usage: python tools/gen_aircraft_db.py <specs.json>
The input may be either the raw {"aircraft": {...}} object or a workflow
output wrapper containing it under result.aircraft.
"""
import json
import sys
from pathlib import Path

PRICES = {
    "cessna172": 0, "a320": 45000, "a321": 52000, "b737max8": 55000,
    "b757": 65000, "a340": 90000, "a350": 120000, "b747": 140000,
    "a380": 200000, "an124": 160000, "an225": 250000, "f16": 80000,
    "a10": 70000, "f35": 110000, "f22": 150000, "bell206": 25000,
    "uh60": 60000, "ch47": 95000,
}

# Sane VNE (low-altitude max operating TAS, m/s) windows per role so the
# overspeed rule can't be gamed by a researcher outlier.
VNE_CLAMP = {
    "ga": (70, 130), "airliner": (160, 200), "cargo": (160, 200),
    "fighter": (330, 480), "attack": (180, 260), "helicopter": (45, 95),
}

REQUIRED_PHYSICS = [
    "empty_mass_kg", "max_takeoff_mass_kg", "fuel_capacity_kg", "wing_area_m2",
    "wing_span_m", "oswald", "cl_alpha_per_rad", "cl0", "alpha_stall_deg", "cd0",
    "flap_max_deg", "flap_cl_bonus", "flap_cd_bonus", "has_slats",
    "slat_alpha_bonus_deg", "has_spoilers", "spoiler_cd", "spoiler_lift_kill",
    "engine_type", "engine_count", "max_thrust_n", "max_power_w",
    "afterburner_thrust_n", "fuel_burn_full_kg_s", "spool_rate", "vne_ms",
    "stall_speed_clean_ms", "max_mach", "g_limit_pos", "g_limit_neg",
    "aileron_max_deg", "elevator_max_deg", "rudder_max_deg", "pitch_authority",
    "roll_authority", "yaw_authority", "gear_retractable", "gear_main_x_m",
    "gear_main_z_m", "gear_nose_z_m", "gear_leg_length_m",
    "rotor_main_radius_m", "rotor_tail_radius_m", "tandem_rotors", "max_speed_ms",
]


def gd_value(v, indent=0):
    pad = "\t" * indent
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        if isinstance(v, float) and v == int(v) and abs(v) < 1e12:
            return f"{v:.1f}"
        return repr(v)
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, list):
        return "[" + ", ".join(gd_value(x) for x in v) + "]"
    if isinstance(v, dict):
        lines = [pad + "\t" + json.dumps(k) + ": " + gd_value(val, indent + 1) + ","
                 for k, val in v.items()]
        return "{\n" + "\n".join(lines) + "\n" + pad + "}"
    raise TypeError(type(v))


def main():
    src = Path(sys.argv[1])
    raw = json.loads(src.read_text(encoding="utf-8"))
    aircraft = raw.get("result", raw).get("aircraft", raw.get("aircraft"))
    if aircraft is None:
        sys.exit("no aircraft key found")

    problems = []
    for aid, spec in aircraft.items():
        p = spec["physics"]
        for key in REQUIRED_PHYSICS:
            if key not in p:
                # Derivable fallbacks so a single missing key never breaks the game
                if key == "max_speed_ms":
                    p[key] = p.get("vne_ms", 100)
                else:
                    problems.append(f"{aid}: missing physics.{key}")
        lo, hi = VNE_CLAMP.get(spec["role"], (50, 500))
        if not (lo <= p["vne_ms"] <= hi):
            print(f"  clamp {aid}.vne_ms {p['vne_ms']} -> [{lo},{hi}]")
            p["vne_ms"] = max(lo, min(hi, p["vne_ms"]))
        if p["gear_nose_z_m"] > 0:
            p["gear_nose_z_m"] = -abs(p["gear_nose_z_m"])
        # Main gear must sit far enough behind the CG that a bounce or full
        # elevator can't tip the aircraft onto its tail.
        min_arm = max(0.055 * spec["mesh"]["fuselage_length_m"], 0.45)
        if p["gear_main_z_m"] < min_arm:
            print(f"  clamp {aid}.gear_main_z_m {p['gear_main_z_m']} -> {min_arm:.2f}")
            p["gear_main_z_m"] = round(min_arm, 2)
        spec["price"] = PRICES.get(aid, 50000)

    if problems:
        sys.exit("FATAL missing keys:\n" + "\n".join(problems))

    order = sorted(aircraft.keys(), key=lambda a: (aircraft[a]["price"], a))
    body_lines = []
    for aid in order:
        body_lines.append(f"\t{json.dumps(aid)}: " + gd_value(aircraft[aid], 1) + ",")
    body = "\n".join(body_lines)

    out = f"""class_name AircraftDB
## AUTO-GENERATED by tools/gen_aircraft_db.py from data/aircraft_specs.json.
## Real-world researched specs, SI units. Regenerate rather than hand-editing.

static func ids() -> Array:
\treturn DATA.keys()

static func spec(id: String) -> Dictionary:
\treturn DATA.get(id, DATA["cessna172"])

static func config(id: String) -> AircraftConfig:
\treturn AircraftConfig.from_dict(spec(id))

static func price(id: String) -> int:
\treturn int(spec(id).get("price", 0))

const DATA := {{
{body}
}}
"""
    dest = Path(__file__).resolve().parent.parent / "data" / "AircraftDB.gd"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(out, encoding="utf-8", newline="\n")
    print(f"wrote {dest} with {len(aircraft)} aircraft: {', '.join(order)}")


if __name__ == "__main__":
    main()
